### ISSUE TITLE
Cryptic API Message 

### ISSUE THREAD

**Issue by martinbe1io** [chirpstack/chirpstack#312]
Hi, 

using latest chirpstack api v4; creation of device profiles and devices works, when I want to activate a device following error message appears:

***io.grpc.StatusRuntimeException: INTERNAL: Invalid string length***

as I use the eui multiple times this should not be the issue; appSKey is in hex format; would expect this is correct (see logs below)
any hints ? what string length is invalid? 

thx a lot

```
           log.info("Deviceactivation deveui={} appkey={}",deviceeui,appkey);
	   DeviceActivation activation=DeviceActivation.newBuilder()
			   .setDevEui(deviceeui)
			   .setAppSKey(appkey.toLowerCase())
			   .build();
	   log.info("activating device {}",activation); 
	   ActivateDeviceRequest activaterequest=ActivateDeviceRequest
			   .newBuilder()
			   .setDeviceActivation(activation)
			   .build(); 
	   deviceservicestub.activate(activaterequest);
```

Detailed message log

```
[2023-10-28 18:14:10,765]-[JobFactory-jobexecution-6a0e5bdb-5090-4586-9c88-9a6f8ba409b5] INFO  io.be1.circular.externalassets.ExternalAssetProviderChirpStack usr=mf@martinfluch.com sid= - Deviceactivation deveui=8cf95720000xxxxx appkey=2B7E151628AED2A6ABF7158809CXXXXX
[2023-10-28 18:14:10,768]-[JobFactory-jobexecution-6a0e5bdb-5090-4586-9c88-9a6f8ba409b5] INFO  io.be1.circular.externalassets.ExternalAssetProviderChirpStack usr=mf@martinfluch.com sid= - activating device dev_eui: "8cf95720000xxxxx"
app_s_key: "2b7e151628aed2a6abf7158809cXXXXX"

[2023-10-28 18:14:11,015]-[JobFactory-jobexecution-6a0e5bdb-5090-4586-9c88-9a6f8ba409b5] ERROR io.be1.circular.externalassets.ExternalAssetProviderChirpStack usr=mf@martinfluch.com sid= - an error occured: afterupdatestatus io.grpc.StatusRuntimeException: INTERNAL: Invalid string length
[2023-10-28 18:14:11,015]-[JobFactory-jobexecution-6a0e5bdb-5090-4586-9c88-9a6f8ba409b5] ERROR io.be1.circular.externalassets.ExternalAssetProviderChirpStack usr=mf@martinfluch.com sid= - stacktrace: io.grpc.StatusRuntimeException: INTERNAL: Invalid string length
	at io.be1.circular.my-app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.be1.circular.my-app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.be1.circular.my-app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at io.be1.circular.my-app//io.chirpstack.api.DeviceServiceGrpc$DeviceServiceBlockingStub.activate(DeviceServiceGrpc.java:1416)
	at io.be1.circular.my-app//io.be1.circular.externalassets.ExternalAssetProviderChirpStack.registerDevice(ExternalAssetProviderChirpStack.java:910)
	at io.be1.circular.my-app//io.be1.circular.externalassets.ExternalAssetProviderChirpStack.afterUpdatestatus(ExternalAssetProviderChirpStack.java:513)
	at io.be1.circular.my-app//io.be1.circular.externalassets.ExternalAssetProviderBase.updateStatus(ExternalAssetProviderBase.java:723)
	at io.be1.circular.my-app//io.be1.circular.externalassets.ExternalAssetProviderBase.updateStatus(ExternalAssetProviderBase.java:645)
	at io.be1.circular.my-app//io.be1.circular.externalassets.ExternalAssetManagerModule.deployExternalAsset(ExternalAssetManagerModule.java:1069)
	at io.be1.circular.my-app//io.be1.circular.assets.AssetsMvcBase.deployExternalAsset(AssetsMvcBase.java:1561)
	at io.be1.circular.my-app//io.be1.circular.assets.AssetsMvcBase.deployExternalAssets(AssetsMvcBase.java:1447)
	at io.be1.circular.my-app//io.be1.circular.assets.AssetsMvcBase.create(AssetsMvcBase.java:4424)
	at io.be1.circular.my-app//io.be1.circular.assets.AssetsMvcBase.handleJob(AssetsMvcBase.java:4533)
	at io.be1.circular.my-app//io.be1.circular.assets.AssetsMvcBase.executeJob(AssetsMvcBase.java:2914)
	at io.be1.circular.my-app//io.be1.circular.platformtools.job.JobFactory.lambda$executejob$1(JobFactory.java:691)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by martinbe1io** [comment]
Fixed, there is no need for activation as it autoactivates when OTAA keys are set correctly

```
	   DeviceKeys keys=DeviceKeys.newBuilder()
			   .setDevEui(deviceeui)
			   //.setAppKey(appkey.toLowerCase())
			   .setNwkKey(appkey.toLowerCase())
			   .build();
			   
	   
	   CreateDeviceKeysRequest createdevicekeys=CreateDeviceKeysRequest.newBuilder()
			   .setDeviceKeys(keys)
			   .build();
			
	   	   
	   log.info("setting keys  {}",createdevicekeys);
	   deviceservicestub.createKeys(createdevicekeys);

```
